GET http://localhost:4000/me

###
GET http://localhost:4000/heroes

###
POST http://localhost:4000/heroes
Content-Type: application/json

{
	"id": "69",
	"name": "Batman",
	"powerstats": {
		"intelligence": "81",
		"strength": "40",
		"speed": "29",
		"durability": "55",
		"power": "63",
		"combat": "90"
	},
	"biography": {
		"full-name": "Terry McGinnis",
		"alter-egos": "No alter egos found.",
		"aliases": ["The Tomorrow Knight"],
		"place-of-birth": "Gotham City, 25th Century",
		"first-appearance": "Batman Beyond #1",
		"publisher": "DC Comics",
		"alignment": "good"
	}
}

###
GET http://localhost:4000/heroes/60e46dad8e9aa63e9ce37324

###
GET http://localhost:4000/heroes/bio/60e564b2beb9654834d77596

###
DELETE http://localhost:4000/heroes/60e59f686174306c8c4e6440

###
PATCH http://localhost:4000/heroes/60e5a656f8aa5f1f5002dad6
Content-Type: application/json

{
	"biography.full-name": "Bruce Wayne"
}

###
POST http://localhost:4000/users
Content-Type: application/json

{
	"email": "medhi3@email.com",
	"password": "me",
	"role": "user"
}

###
GET http://localhost:4000/users

###
GET http://localhost:4000/users/60e5c047c179526850bdc822


###
PATCH http://localhost:4000/users/60e5c047c179526850bdc822
Content-Type: application/json

{
	"password": "secret"
}

###
DELETE http://localhost:4000/users/60e5c047c179526850bdc822


###
POST http://localhost:4000/login
Content-Type: application/json

{
	"email": "medhi2@email.com",
	"password": "medhi"
}

###
GET http://localhost:4000/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZTZkMTU4NjdhZGI1M2NkY2JhY2FhYSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjI1NzUzOTQyfQ.bSuxO2z_-ZDXtFZ4bgvqucrkNqDML2e81rxrXXnxzKo
